name: share_api
description: Flutter Plugin for sharing contents to social media, either from System UI, or directly to the target application. Currently supports Facebook Story and Instagram Story in Android.
version: 0.0.7
author: Albert Richard Sanyoto <me@albertalrisa.com>
homepage: https://github.com/albertalrisa/share_api

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.3.0
  path: ^1.6.4

flutter:
  plugin:
    androidPackage: com.albertalrisa.flutter.plugins.shareapi
    pluginClass: ShareApiPlugin